eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
  instance:
      hostname: localhost
okta:
  oauth2:
    issuer: https://dev-02875322.okta.com/oauth2/default
    audience: api://default
