eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
okta:
  oauth2:
    issuer: https://dev-02875322.okta.com/oauth2/default
    audience: api://default
spring:
  zipkin:
    baseUrl: http://zipkin:9411
