eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
      hostname: eureka-0
okta:
  oauth2:
    issuer: https://dev-02875322.okta.com/oauth2/default
    audience: api://default
